### ISSUE TITLE
Team Consistencies

### ISSUE THREAD

**Issue by ShooShoSha** [CoreModding/Craftable-Enchantments#2]
We need to agree on a few conventions and formatting. I do not want to fight about tab length or spaces. Also every commit message needs to be meaningful, not just "stuff happened".

**Comment by NrdyN8** [comment]
What do you have in mind for conventions?

**Comment by ghost** [comment]
Tab length: 4 spaces. MUST be spaces.
Imports must be organized.
Spelling must be correct.
EVERYTHING of public access (public method, public class, public constructor) must have javadoc.
There must be 1 space between methods, and NO spaces at:
- The end of methods
- The end of classes
- Ect

And in the future, NO SUPPRESSWARNINGS. Aside from "boxing". I have put some but no more should exist.
Code should be simple enough to understand that there are no comments needed in it. There should be next to 0 comments, anywhere.
No unneeded elses. Example:
if(testfor) {
    _stuff happens here_
    return something;
}
else {
    return somethingElse;
}

The else is not needed.

2 other things added there:
1 space between if and curly bracket. And no boolean ==. Just put the BOOLEAN or !boolean. There should be no boolean == true or boolean == false. It should be just if(boolean) or if (!boolean).

No capitals in packages.
Names like doSomething, not DoSomething or dosomething. Classes would be SomethingElse, not somethingElse or somethingelse.
Variables are grouped by access restrictions and type in most cases. Like:

public static int blah;
public static int blah2;

public static String blah6;
public static String blah7;

public int blah3;
public int blah4;

public String blah8;

private int blah5;

That format isnt perfect and could use changes.

Oh, and yet again, this really gets on my nerves:

public class Class {

```
public String blah;

public void doSomething(){

}
                      <---- AAAUUUUUGGGGHHHH!!!!!!
```

}

No blank catches. Either actually HANDLE it, or do e.printStackTrace();
Use ternary operators if it makes sense to. Dont have if chains if you dont need to.
Do method chaining where it makes sense.
All javadoc needs all params, returns, and throws.
No author tags in javadoc.
Keep code as simple as possible. We are a team. Do NOT write code that wouldnt be easy for others to edit. Also, do not sacrifice code style for optimizations unless they are REALLY needed! I see all the time where people will make code extremely complicated to save a half second of loading time, and then it being impossible to edit and tons of bugs appearing in it (but nobody can find what's wrong)

I'll put more later once I think of it.

**Comment by ShooShoSha** [comment]
Out of curiosity, are you familiar with http://www.goodreads.com/book/show/3735293-clean-code

**Comment by ghost** [comment]
No.

**Comment by ShooShoSha** [comment]
I recommend it. A good read and helpful with refactoring code. Have you set up eclipse with all the formatting rules? If you would export that formatting, we could all use it.

One of my biggest issues are the commit messages. I try to make a message for each task implemented (even if I make dozens of commits). The intent behind all of the messages is clear communication why it helps the project at hand.

**Comment by ghost** [comment]
I don't use eclipse anymore. And it's considered bad to have tons of
commits as it destroys the project history.

**Comment by ShooShoSha** [comment]
That poses a convention problem: eclipse is the preferred IDE for Forge.

**Comment by ghost** [comment]
There is no preferred IDE for forge...

**Comment by ShooShoSha** [comment]
Who considers many commits bad? Much of the community follows "commit early and often". 
http://sethrobertson.github.io/GitBestPractices/
http://kentnguyen.com/development/visualized-git-practices-for-team/

And if you are worried about a "messy" history, there are methods of cleaning it:
http://tom.preston-werner.com/2009/05/19/the-git-parable.html

**Comment by ghost** [comment]
I'm just saying it is. I do it myself xP

We might as well do that though. It's just other developers often consider
it bad.

**Comment by ShooShoSha** [comment]
I will get an eclipse formatting XML with your guidelines for those who may use it.

**Comment by eikap** [comment]
Give me one reason why i shouldn't use tabs?

**Comment by InternetAthiest** [comment]
Tabs are quicker than 4 spaces and also Eclipse does it automaticly. Also you can't order somebody to change his/her coding style it is like asking somebody to change his/her Writing style, Everybodys different

**Comment by ghost** [comment]
He just likes eclipse? So what? Why would he add the command to set it up
for IntelliJ? Do you know what CPW uses?

And mushroom, please tell me you aren't serious.

**Comment by eikap** [comment]
I am serious

**Comment by ghost** [comment]
Proof, it's a simple config change to make it do 4 spaces rather then a tab.

**Comment by ghost** [comment]
I did some heavy eclipse config for formatting, javadoc, and code settings.
But.... where did they go :L

I need to upload them.

**Comment by ghost** [comment]
Continue this here:
https://github.com/CoreModding/Group/issues/1
