### ISSUE TITLE
Minecraft version

### ISSUE THREAD

**Issue by eikap** [CoreModding/Craftable-Enchantments#3]
Why are you developing for both 1.7.2 and 1.6.4, but you made more progress in the 1.6.4 branch, we develop our mods for 1.7.2, and I was told to work on this project so it'd be finished faster, so could you make a todo or something like that so i'd know what you have done, what you're working on, and what needs to be done, so I could work on something else.

**Comment by NrdyN8** [comment]
It is a 1.6.4 mod. It was started in 1.7 and then backdated.

**Comment by ghost** [comment]
Uhm, why?

**Comment by NrdyN8** [comment]
That is what was asked when it was requested.

**Comment by eikap** [comment]
Ok, then im sorry but i cant help in the development.

**Comment by ghost** [comment]
Same.

**Comment by NrdyN8** [comment]
No worries. I will help with it.
