### ISSUE TITLE
Enchantments Apply to New Tools Only

### ISSUE THREAD

**Issue by ShooShoSha** [CoreModding/Craftable-Enchantments#6]
Items must have full durability for enchantment to be used.

EDIT: Only tools with full durability can be enchanted. It should be any tool regardless  of damage.

**Comment by ghost** [comment]
No, that ISNT the right topic. I wonder why it bugged.

I'd reply to your post but I was temp banned for alternate accounts, even
though it was a friend's account and CoreModding.

**Comment by ShooShoSha** [comment]
I see it as a bug right now. Right now only new tools can have the enchantment applied. I believe any tool regardless of damage should have an enchantment applied.

Need to figure out how to get the tool in the crafting table and apply the enchant to it instead of making a new tool.

**Comment by ShooShoSha** [comment]
This was fixed when the recipes were add onto the items. See issue #5
