### ISSUE TITLE
Conventions issue

### ISSUE THREAD

**Issue by ghost** [CoreModding/Craftable-Enchantments#7]
The master branch must be 1.7.

Also, REMOVE THE STUPID PRE-INIT CLASS. Just stick the calls in preinit! It's pointless to make another class and just reduces code cleanness, and is harder to do.

**Comment by NrdyN8** [comment]
It doesn't have to be 1.7. It is up to the person that requested it.

**Comment by ShooShoSha** [comment]
That pre init class follows clean code principles and OO design. It keeps the code clean by making the main mod class less mutable and follows OO design through the proxy pattern when initializing heavy or many objects.

http://www.oodesign.com/proxy-pattern.html

**Comment by ShooShoSha** [comment]
The point of branches are for developing features that may merge with other branches. The master branch, in this case, will be the recommended version. When the client asks for an update, there will be a branch we can springboard from and merge when finished.

**Comment by ShooShoSha** [comment]
Lastly, do not open and close an issue without hearing from the person you're submitting the issue. Two problems: you do not hear explanations with possible new insight and the issue is not resolved rather it is usurped then deemed resolved.

We're a team here. On GitHub we have the opportunity to develop new ideas socially with discussion. Post problems, ask for solutions, and discuss.

**Comment by ghost** [comment]
It's ugly to have another class, and it's 2 lines of code. We really need a
new class and new method to handle 2 lines of code? That issue was handled
by rather then having all the itemreg ect in 1 class putting it in other
classes, making the PreInit class worthless. If you DIDNT have those to
already compress it so much, I'd agree.

Also, the reason for the all mods main branches being 1 version is most
people have 1 workspace for 1 forge version for all of the mods. If they
dont have all of the mods, or multiple forge instances, it's just being
wasteful of resources and space.

Either way, I have no intention of making a huge mess of having multiple
forge, downloading multiple branches, constantly changing and moving
projects, ect.

**Comment by ShooShoSha** [comment]
That preinit class will grow. It is two lines now, but if I need to change, there are fewer classes to change and fewer chances code will break. I thought of having a single initialize class to handle all the events, but it may change too often.

That is how my environment is setup. I develop in 1.6.4 and 1.7.2 simultaneously. When you muck with the master branch, it makes my work harder.

If you wish to contribute, setup multiple Forge environments or checkout the appropriate branch. If the need arises, the master branch will be deleted to enforce development in the correct branch. That way you may keep your single workspace, forge version environment and enable multiple version environments.

**Comment by ghost** [comment]
_Im saying make the main branch 1.7 and the side branches whatever you
want. Also, more classes = more chance of code breaking as it creates a
complex mess._

**Comment by ShooShoSha** [comment]
I've made a separate issue concerning the branches in CoreModding/Craftable-Enchantments#8
