### ISSUE TITLE
Change Default Branch

### ISSUE THREAD

**Issue by ShooShoSha** [CoreModding/Craftable-Enchantments#8]
Relating issue discussed in CoreModding/Group#1

Eliminate confusion and frustration over branches. Primarily the team develops for 1.7.2, but there are a few projects that are developed in 1.6.4 and needs specificity.

**Comment by ShooShoSha** [comment]
Change through settings on the main repository page. Under repository name, a drop-down box shows the branches. Select the appropriate branch to be the default.

**Comment by ShooShoSha** [comment]
Changed default branch from 'master' to '1.7.2'.

**Comment by ShooShoSha** [comment]
Didn't mean to close until someone else confirms.

**Comment by ghost** [comment]
Yes that's fine.
